name: M2D-LIF
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/msys2/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - bzip2=1.0.8=h7f98852_4
  - ca-certificates=2022.9.24=ha878542_0
  - ld_impl_linux-64=2.39=hc81fddc_0
  - libffi=3.4.2=h7f98852_5
  - libgcc-ng=12.2.0=h65d4601_19
  - libgomp=12.2.0=h65d4601_19
  - libnsl=2.0.0=h7f98852_0
  - libsqlite=3.40.0=h753d276_0
  - libuuid=2.32.1=h7f98852_1000
  - libzlib=1.2.13=h166bdaf_4
  - ncurses=6.3=h27087fc_1
  - openssl=3.0.7=h166bdaf_0
  - pip=22.3.1=pyhd8ed1ab_0
  - python=3.10.6=ha86cf86_0_cpython
  - readline=8.1.2=h0f457ee_0
  - setuptools=65.5.1=pyhd8ed1ab_0
  - sqlite=3.40.0=h4ff8645_0
  - tk=8.6.12=h27826a3_0
  - tzdata=2022f=h191b570_0
  - wheel=0.38.4=pyhd8ed1ab_0
  - xz=5.2.6=h166bdaf_0
  - pip:
    - absl-py==2.2.2
    - asttokens==3.0.0
    - certifi==2025.1.31
    - charset-normalizer==3.4.1
    - contourpy==1.3.1
    - cycler==0.12.1
    - decorator==5.2.1
    - exceptiongroup==1.2.2
    - executing==2.2.0
    - filelock==3.18.0
    - fonttools==4.56.0
    - fsspec==2025.3.0
    - grpcio==1.71.0
    - idna==3.10
    - imageio==2.37.0
    - ipython==8.36.0
    - jedi==0.19.2
    - jinja2==3.1.6
    - kiwisolver==1.4.8
    - lazy_loader==0.4
    - markdown==3.8
    - markupsafe==3.0.2
    - matplotlib==3.10.1
    - matplotlib-inline==0.1.7
    - mpmath==1.3.0
    - networkx==3.4.2
    - numpy==1.24.4
    - nvidia-cublas-cu12==12.1.3.1
    - nvidia-cuda-cupti-cu12==12.1.105
    - nvidia-cuda-nvrtc-cu12==12.1.105
    - nvidia-cuda-runtime-cu12==12.1.105
    - nvidia-cudnn-cu12==8.9.2.26
    - nvidia-cufft-cu12==11.0.2.54
    - nvidia-curand-cu12==10.3.2.106
    - nvidia-cusolver-cu12==11.4.5.107
    - nvidia-cusparse-cu12==12.1.0.106
    - nvidia-nccl-cu12==2.18.1
    - nvidia-nvjitlink-cu12==12.8.93
    - nvidia-nvtx-cu12==12.1.105
    - opencv-python==4.11.0.86
    - packaging==24.2
    - pandas==2.2.3
    - parso==0.8.4
    - pexpect==4.9.0
    - pillow==11.1.0
    - prompt_toolkit==3.0.51
    - protobuf==6.30.2
    - psutil==7.0.0
    - ptyprocess==0.7.0
    - pure_eval==0.2.3
    - py-cpuinfo==9.0.0
    - pygments==2.19.1
    - pyparsing==3.2.3
    - python-dateutil==2.9.0.post0
    - pytz==2025.2
    - pyyaml==6.0.2
    - requests==2.32.3
    - scikit-image==0.25.2
    - scipy==1.15.2
    - seaborn==0.13.2
    - sentry-sdk==2.27.0
    - six==1.17.0
    - stack-data==0.6.3
    - sympy==1.13.3
    - tensorboard==2.19.0
    - tensorboard-data-server==0.7.2
    - thop==0.1.1.post2209072238
    - tifffile==2025.5.10
    - torch==2.1.0
    - torchaudio==2.1.0
    - torchvision==0.16.0
    - tqdm==4.67.1
    - traitlets==5.14.3
    - triton==2.1.0
    - typing_extensions==4.12.2
    - ultralytics==8.1.44
    - ultralytics-thop==2.0.14
    - urllib3==2.3.0
    - wcwidth==0.2.13
    - werkzeug==3.1.3
prefix: /home/zhaotianyi/anaconda3/envs/yolov8

